# source: https://github.com/sindre0830/Workflow-Templates
name: CMake workflow
# when to run the workflow
on:
  push:
    paths:
    - '.github/workflows/cmake.yml'
    - 'path/to/folder/**'
  pull_request:
  workflow_dispatch:
# instructions the workflow will perform
jobs:
  build:
    # environment to run on
    runs-on: ubuntu-latest
    # steps to perform
    steps:
    - uses: actions/checkout@v2

    - name: Set up language
      working-directory: ./path/to/folder
      run: |
        sudo apt-get update
        sudo apt-get install gcc g++ cmake python3-pip
        pip3 install cpplint
        mkdir Build

    - name: Install dependencies
      working-directory: ./path/to/folder
      run: cmake ./..

    - name: Build program
      working-directory: ./path/to/folder
      run: cmake --build .

    - name: Syntax checker
      working-directory: ./path/to/folder
      run: cpplint --root=. --linelength=150 --filter=-build/include_subdir --recursive --exclude=External/* --exclude=Build/* *
