# source: https://github.com/sindre0830/Workflow-Templatess
name: Name of workflow
# when to run the workflow
on:
  push:
  - '.github/workflows/golang.yml'
  - 'path/to/folder/**'
  pull_request:
  workflow_dispatch:
# instructions the workflow will perform
jobs:
  build:
    # environment to run on
    runs-on: ubuntu-latest
    # steps to perform
    steps:
    - uses: actions/checkout@v2

    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build program
      working-directory: ./path/to/folder
      run: go build -v ./main.go

    - name: Run tests
      working-directory: ./path/to/folder
      run: go test -v ./...
