# source: https://github.com/sindre0830/Workflow-Templates
name: Name of workflow
# when to run the workflow
on:
  push:
  - '.github/workflows/python.yml'
  - 'path/to/folder/**'
  pull_request:
# instructions the workflow will perform
jobs:
  build:
    # environment to run on
    runs-on: ubuntu-latest
    # steps to perform
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.10'

    - name: Install dependencies
      working-directory: ./path/to/folder
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip freeze > requirements.txt
        pip install flake8

    - name: Build program
      working-directory: ./path/to/folder
      run: python -m py_compile ./main.py

    - name: Syntax checker
      working-directory: ./path/to/folder
      run: flake8 . --max-line-length 150
