# source: https://github.com/sindre0830/Workflow-Templates
name: Name of workflow
# when to run the workflow
on:
  push:
  - '.github/workflows/rust.yml'
  - 'path/to/folder/**'
  pull_request:
# instructions the workflow will perform
jobs:
  build:
    # environment to run on
    runs-on: ubuntu-latest
    # steps to perform
    steps:
    - uses: actions/checkout@v2

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Build program
      working-directory: ./path/to/folder
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Run tests
      working-directory: ./path/to/folder
      uses: actions-rs/cargo@v1
      with:
        command: test

    - name: Syntax checker (fmt)
      working-directory: ./path/to/folder
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Syntax checker (clippy)
      working-directory: ./path/to/folder
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
