# source: https://github.com/sindre0830/Workflow-Templatess
name: Golang workflow
# when to run the workflow
on:
  push:
    paths:
    - '.github/workflows/golang.yml'
    - 'examples/golang/**'
  pull_request:
  workflow_dispatch:
# instructions the workflow will perform
jobs:
  build:
    # environment to run on
    runs-on: ubuntu-latest
    # steps to perform
    steps:
    - uses: actions/checkout@v3

    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.16'
        cache: true

    - name: Build program
      working-directory: examples/golang
      run: go build -v ./main.go

    - name: Run tests
      working-directory: examples/golang
      run: go test -v ./...
