# source: https://github.com/sindre0830/Workflow-Templates
name: Name of workflow
# when to run the workflow
on:
  push:
  - 'path/to/folder/**'
  pull_request:
# instructions the workflow will perform
jobs:
  build:
    # environment to run on
    runs-on: ubuntu-latest
    # steps to perform
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '17.x'

    - name: Install dependencies
      working-directory: ./path/to/folder
      run: npm install

    - name: Build program
      working-directory: ./path/to/folder
      run: npm run build --if-present

    - name: Run tests
      working-directory: ./path/to/folder
      run: npm tests
