# source: https://github.com/sindre0830/Workflow-Templates
name: Node workflow
# when to run the workflow
on:
  push:
    paths:
    - '.github/workflows/node.yml'
    - 'examples/node/**'
  pull_request:
  workflow_dispatch:
# instructions the workflow will perform
jobs:
  build:
    # environment to run on
    runs-on: ubuntu-latest
    # steps to perform
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '17.x'
        cache: 'npm'

    - name: Install dependencies
      working-directory: examples/node
      run: npm install

    - name: Build program
      working-directory: examples/node
      run: npm run build --if-present

    - name: Run tests
      working-directory: examples/node
      run: npm tests
