# source: https://github.com/sindre0830/Workflow-Templates
name: Rust workflow
# when to run the workflow
on:
  push:
    paths:
    - '.github/workflows/rust.yml'
    - 'examples/rust/**'
  pull_request:
  workflow_dispatch:
# instructions the workflow will perform
jobs:
  build:
    # environment to run on
    runs-on: ubuntu-latest
    # steps to perform
    steps:
    - uses: actions/checkout@v2

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Build program
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --manifest-path examples/rust/Cargo.toml

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path examples/rust/Cargo.toml

    - name: Syntax checker (fmt)
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check --manifest-path examples/rust/Cargo.toml

    - name: Syntax checker (clippy)
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings --manifest-path examples/rust/Cargo.toml
